NiboBankConciliator.Mvc/Models/ErrorViewModel.cs
using System;

namespace NiboBankConciliator.Mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NiboBankConciliator.Mvc/Controllers/BankAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NiboBankConciliator.Core.Services;

namespace NiboBankConciliator.Mvc.Controllers
{
    public class BankAccountsController : Controller
    {
        readonly IBankReconciliationService _bankReconciliationService;
        public BankAccountsController(IBankReconciliationService bankReconciliationService)
        {
            _bankReconciliationService = bankReconciliationService;
        }

        // GET: BankAccountsController
        public ActionResult Index()
        {
            var bankAccounts = _bankReconciliationService.GetBankAccounts();
            return View(bankAccounts);
        }

        // GET: BankAccountsController/Details/5
        public ActionResult Details(int id)
        {
            var bankAccount = _bankReconciliationService.GetBankAccount(id);
            return View(bankAccount);
        }
    }
}

NiboBankConciliator.Mvc/Controllers/BankConciliationsController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NiboBankConciliator.Core;
using NiboBankConciliator.Core.Entities;
using NiboBankConciliator.Core.Services;

namespace NiboBankConciliator.Mvc
{
    public class BankConciliationsController : Controller
    {
        readonly IBankReconciliationService _bankReconciliationService;
        public BankConciliationsController(IBankReconciliationService bankReconciliationService)
        {
            _bankReconciliationService = bankReconciliationService;
        }

        // GET: BankConciliationsController/Reconcile
        public ActionResult Reconcile()
        {
            return View();
        }

        // POST: BankConciliationsController/Reconcile
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Reconcile(IFormCollection formCollection)
        {
            try
            {
                //Should be tested. IFormFileCollection should be in Core Framework?
                var ofxDocuments = new List<OfxDocument>();
                foreach (var file in formCollection.Files)
                {
                    var stream = file.OpenReadStream();
                    var ofxDocument = OfxDocumentParser.Parse(stream);
                    ofxDocuments.Add(ofxDocument);
                }
                var bankAccount = _bankReconciliationService.ReconcileAndAddTransactions(ofxDocuments);

                return View(nameof(Reconcile), bankAccount);
            }
            catch
            {
                return View();
            }
        }
    }
}

NiboBankConciliator.Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NiboBankConciliator.Mvc.Models;

namespace NiboBankConciliator.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NiboBankConciliator.Mvc/Views/BankAccounts/Details.cshtml
@model NiboBankConciliator.Core.Entities.BankAccount

@{
    ViewData["Title"] = $"Transactions - {Model.AccountID}";
}

<div>
    <h4>BankAccount</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BankID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BankID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccountID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccountID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccountType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccountType)
        </dd>
    </dl>
</div>
<div>
    <h4>Transactions</h4>

    @{ await Html.RenderPartialAsync("_BankTransactions", Model.Transactions); }
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

NiboBankConciliator.Mvc/Views/BankAccounts/Index.cshtml
@model IEnumerable<NiboBankConciliator.Core.Entities.BankAccount>

@{
    ViewData["Title"] = "Bank Accounts";
}

<h1>Bank Accounts</h1>

@if (Model != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BankID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AccountID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AccountType)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BankID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AccountID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AccountType)
                    </td>
                    <td>
                        @Html.ActionLink("Transactions", "Details", new { id = item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

NiboBankConciliator.Mvc/Views/BankAccounts/Transactions.cshtml
@model NiboBankConciliator.Core.Entities.BankAccount

@{
    ViewData["Title"] = $"Transactions - {Model.AccountID}";
}

<h1>Details</h1>

<div>
    <h4>BankAccount</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BankID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BankID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccountID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccountID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccountType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccountType)
        </dd>
    </dl>
</div>

@Html.RenderPartialAsync("_BankTransactions", Model.Transactions);

<div>
    <a asp-action="Index">Back to List</a>
</div>

NiboBankConciliator.Mvc/Views/BankConciliations/Reconcile.cshtml
@model NiboBankConciliator.Core.Entities.BankAccount
@{
    ViewData["Title"] = "Reconcile";
}

<h1>Reconcile</h1>
<hr />
<div class="row">
    <div class="col-md-12">
        <form method="post" class="file-uploader" action="" enctype="multipart/form-data">
            <div class="file-uploader__message-area">
                <p>Select the OFX Documents</p>
            </div>
            <div class="file-chooser">
                <input name="files" class="file-chooser__input" type="file" multiple>
            </div>
            <input class="file-uploader__submit-button" type="submit" value="Reconcile">
        </form>
    </div>
</div>

@if (Model != null)
{
    <h2>Account</h2>
    @Html.DisplayForModel();
    <br />
    <h2>Transactions</h2>
    await Html.RenderPartialAsync("_BankTransactions", Model.Transactions);
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/multiple-file-uploader.js"></script>
}

NiboBankConciliator.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Nibo Bank Conciliator";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the Nibo Bank Conciliator! Great Accountant!</h1>
</div>

NiboBankConciliator.Mvc/Views/Shared/_BankTransactions.cshtml
@model IEnumerable<NiboBankConciliator.Core.Entities.BankTransaction>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TransType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TransAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatePosted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Memo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TransType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TransAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatePosted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Memo)
            </td>
        </tr>
}
    </tbody>
</table>

NiboBankConciliator.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nibo Bank Conciliator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/reconcile.css" />
    <link rel="stylesheet" href="~/css/multiple-file-uploader.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Nibo Bank Conciliator</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BankConciliations" asp-action="Reconcile">Reconcile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BankAccounts" asp-action="Index">Bank Accounts</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Nibo Bank Conciliator
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>